spring.application.name=inventory-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=inventory_user
spring.datasource.password=inventory_password

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
